import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/header";

const roboto = Roboto({ subsets: ["latin", "cyrillic", "greek"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font--roboto-custom"
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} max-w-7xl mx-auto p-4`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
